### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by xloem** [supernifty/port-forwarder#1]
hey, found this from google, great and convenient work you made here

be nice to upgrade to python3 of course

**Comment by supernifty** [comment]
Thanks @xloem - I'll see what I can do :)

**Comment by Miniontoby** [comment]
I fixed the problem with PR #2 by converting all the scripts using `futurize` from the [`future`](https://python-future.org/quickstart.html) project

**Comment by supernifty** [comment]
Thanks @Miniontoby!
